server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atinsingh/cloudconfig.git
          clone-on-start: false
          skip-ssl-validation: true
